server:
   port: 8000
   
spring: 
   jpa:
      hibernate.ddl-auto: create
      database-platform: org.hibernate.dialect.H2Dialect
   datasource:
      url: jdbc:h2:mem:aluno
      driverClassName: org.h2.Driver
      username: root
      password: toor
   h2:
      console:
         enabled: true
         path: /h2
         settings:
            web-allow-others: true